### ISSUE TITLE
encoding of Chinese characters from webpage converted unsuccessfully

### ISSUE THREAD

**Issue by iaotin** [Microsoft/RTVS#1268]
`id <- 1:5`
`url <- paste0(
  "http://faxian.smzdm.com/mall/%E4%BA%AC%E4%B8%9C/p",
  id)`
` read_html(url[1], encoding = "UTF-8") %>% html_nodes("h2.itemName") %>% html_node("a") %>% html_node("span.black") %>% html_text() %>% repair_encoding(., from = "UTF_8")`

Which gives the result shown below

![qq 20160314110417](https://cloud.githubusercontent.com/assets/1329549/13734071/04e74fdc-e9d5-11e5-8c8c-d5384b940bb2.png)

The Chinese characters are displayed wrongly.
While in R Studio, things go well, though still need to be converted.

Locale: China
System: Windows 10 Pro x64

**Comment by smortaz** [comment]
thanks for filing this.  we'll take a look

**Comment by int19h** [comment]
Likely a dupe of #1211. It seems that we're having problem with multibyte locales?

**Comment by jflam** [comment]
See if dupe and close if is.

**Comment by int19h** [comment]
Also seems to affect Variable Explorer.

**Comment by int19h** [comment]
When trying to repro this, in either RTVS or RS or Rgui, I'm seeing the following output:
```
> read_html(url[1], encoding = "UTF-8") %>% html_nodes("h2.itemName") %>% html_node("a") %>% html_node("span.black") %>% html_text() %>% repair_encoding(., from = "UTF_8")
 [1] "MI \032\032 Note \032\032 \032\032\0324G\032"                                                                
 [2] "\032\032\032\032SONY \032\032 NW-A25HN \032\032\032 \032\032\032\032\032"                                    
 [3] "\032\032\032\032ASUS \032\032 RT-AC68U 1900M \032\032\032\032\032\032\032"                                   
 [4] "\032\032\032\032SNOWKIDS MFi\032\032 Lightning \032\032 1\032 \032\032\032"                                  
 [5] "SAMSUNG \032\032 UA50JS7200JXXZ 50\032\032 4K\032\032 \032\032\032\032"                                      
 [6] "\032\032\032\032Hisense \032\032 LED60EC550A 60\032\032 \032\032\032\032"                                    
 [7] "\032\032\032\032PETRUS \032\032 PE5386 38L \032\032\032"                                                     
 [8] "\032\032\032\032Bestday \032\032\032\032 ZYJ-933 \032\032\032\032\032\032"                                   
 [9] "BRAUN \032\032 \032\032-B D10 \032\032\032\032\032 \032\032\032\032\032\032\032\032\032 \032\032\032\032\032"
[10] "Royalstar \032\032\032 RX-16Y \032\032\032 \032\032\032"                                                     
[11] "13\0320\032\032\032\032\032\032QLT \032\032\032 T1210BB \032\032\032\032 \032\032\032"                       
[12] "FEIDIAO \032\032 FD-i13 \032\0321.8m\032\032\032\032 \032\032\032"                                           
[13] "BRAUN \032\032 MG5010 \032\032\032 \032\032\032\032\032"                                                     
[14] "audio-technica \032\032\032 ATH-CKR9 \032\032\032\032\032\032\032\032"                                       
[15] "\032\032\032\032\032\032\032\032 \032\032\032\032108g"                                                       
[16] "SONY \032\032 SRS-X55 \032\032\032\032\032\032\032\032"                                                      
[17] "HOME SHUANGJIAN \032\032\032\032 SJ-1709 \032\032 +\032\032\032 CJ4"                                         
[18] "\032\032\032\032\032\032\032\032 \032\032\032\032\032\032\032\032\032\032"                                   
[19] "ARS \032\032 \032\032\032\032\032\032\032\032\032\032\032\032\0325\032/\032*2\032"                           
[20] "\032\032\032\032zioxx \032\032 \032\032\032 \032\032\032\0327+\032\032\032\0327"    
```     
This is regardless of the locale - whether it's set to en-US or Chinese:
```
> Sys.getlocale()
[1] "LC_COLLATE=Chinese (Simplified)_China.936;LC_CTYPE=Chinese (Simplified)_China.936;LC_MONETARY=Chinese (Simplified)_China.936;LC_NUMERIC=C;LC_TIME=Chinese (Simplified)_China.936"
```
It might be that something has changed in the website that was being scraped, such that this pipeline no longer does appropriate re-encoding.

I'm pretty sure that the original issue with output is the same as #1340, and so it should be fixed by the same commit. I'm going to close this as dupe for now - please re-open if you are still seeing the issue with the next public RTVS build.

**Comment by iaotin** [comment]
Thanks for your reply.
Well on my system, in RStudio or RGUI, still the same status as below:
![repair](https://cloud.githubusercontent.com/assets/1329549/14482516/2db3ccbc-0170-11e6-88bb-2232eda2aa97.png)
![nonrepair](https://cloud.githubusercontent.com/assets/1329549/14482518/32bf3b38-0170-11e6-90eb-2c37a860ba50.png)
Sorry I didn't try RTVS.
I am wondering it is a system-related or r-core problem, because on my other laptop with Xubuntu 15.10，everything works fine, even without "repairing" the encode:
![_2016-04-13_11-15-00](https://cloud.githubusercontent.com/assets/1329549/14482655/762bf5c2-0171-11e6-8df2-6041d5f5b4e2.png)

**Comment by int19h** [comment]
Would you be interested in testing an early RTVS build that includes the fix for Unicode issues, that I believe will also fix the problem you're having? If so, please ping me at rtvsuserfeedback@microsoft.com.
