### ISSUE TITLE
Missing temporary files in solution explorer

### ISSUE THREAD

**Issue by dawazualex** [Microsoft/RTVS#2304]
Various temporary files are created in my R solution with the file name format [8 a-z/0-9 characters].[3 a-z/0-9 characters]~.  The files cannot be deleted & I cannot find where they are coming from.  The icon is a blue question mark followed by a document icon with a warning triangle over it - 
![image](https://cloud.githubusercontent.com/assets/1669097/18473196/a25df5b0-7989-11e6-8ee1-1eef64867864.png)

I don't have source control on this particular project.

**Comment by MikhailArkhipov** [comment]
These are temporary files that have been since deleted (yellow icon and question mark). R project is not a traditional project and doesn't have list of files. Instead it siply displays what is on disk. When temp file is created it is added to the project automatically and then should be removed when deleted. However, there were bugs (see #1307, #2060 and #2127) fixed in 0.5

**Comment by MikhailArkhipov** [comment]
Now that 0.5 is out, closing. Feel free to reactivate if you still see this in 0.5

**Comment by GaaH** [comment]
I still have this issue. I must unload/reload my project to remove these files.
I'm on VS 2017.

**Comment by Marchen** [comment]
I also have this issue on VS 2017 with R Tools for Visual Studio   1.1.30413.0947.
I found that when I save a file, a new missing item appears in the Solution Explorer.
