### ISSUE TITLE
Will the RTVS plugin be updated to work with VS2019?

### ISSUE THREAD

**Issue by johanrex** [Microsoft/RTVS#4362]
I see that RTVS has been removed from the Data Science Workload in VS 2019. But I assume there's nothing stopping the RTVS plugin to keep being developed and updated for VS 2019 anyway.

What are the plans for the RTVS plugin for VS2019?

**Comment by MikhailArkhipov** [comment]
At its current state RTVS has no standalone installer, it used to be built to participate in the stock VS installer. There are no official plans to further develop RTVS. I might get around and make installable package at some point on my own time, but there is only that much time in a day so I can't make definitive promises.

**Comment by johanrex** [comment]
Thanks for the response. What was the reason for removing RTVS from the VS installer? Low usage? Something else?

**Comment by jwan218** [comment]
We have been using RTVS for quite some time and it is a great tool with my favourite VS style interface. Also it gets a lot more "enterprise experience" to use VS than Rstudio ... 

Please do help to get this great tool work with the new VS, thank you

**Comment by MNRK01** [comment]
I'll put in my perspective on the need for RTVS in VS 2019.

I know that the R community largely uses RStudio, which is an excellent product. But it has only rudimentary support for Python. What is really cool about VS 2017 is that it supports R and Python in a single environment. In my opinion, the Python and R plugins for Visual Studio Code are decent but have miles to go in terms of the experience at the interactive console (e.g. code completion hints). I love the speed improvements to the Python interactive console in Visual Studio 2019 and these make VS an even more compelling environment.

And then there is reality that there is only 1 good IDE for R (yeah that's probably not true. but it is my opinion.). I can't think of another major language where this is the case.

So that's why I am hoping to see that RTVS will be available for VS 2019.

**Comment by jwan218** [comment]
> I'll put in my perspective on the need for RTVS in VS 2019.
> 
> I know that the R community largely uses RStudio, which is an excellent product. But it has only rudimentary support for Python. What is really cool about VS 2017 is that it supports R and Python in a single environment. In my opinion, the Python and R plugins for Visual Studio Code are decent but have miles to go in terms of the experience at the interactive console (e.g. code completion hints). I love the speed improvements to the Python interactive console in Visual Studio 2019 and these make VS an even more compelling environment.
> 
> And then there is reality that there is only 1 good IDE for R (yeah that's probably not true. but it is my opinion.). I can't think of another major language where this is the case.
> 
> So that's why I am hoping to see that RTVS will be available for VS 2019.

you have been saying exactly i wanted to say.  I am quite happy with the current  RTVS even with no improvement. However, if our other development tasks upgraded to VS 2019, that will be ridiculous if i am using the R part on 2017 and that is not efficient that i just keep VS 2017 for the R development.

**Comment by cpl2** [comment]
Definitely feel it's a great shame that RTVS has not been made available for VS 2019. VS 2017 is where we do our R development and we were excited to move across to VS 2019 due to its greater integration with Azure DevOps. The lack of RTVS in VS 2019 is a big roadblock!

**Comment by xianzheTM** [comment]
R's world needs more IDE choices, not just one or two good choices.

**Comment by jpepg4** [comment]
Definitely miss the plug-in.  What would be required to install it without an installer?  Feel like Microsoft should have given this a longer go than effectively 1 edition of Visual Studio.

**Comment by MikhailArkhipov** [comment]
The problem is that some IDE API got deprecated and code needs to be updated, so the issue is not just the installer. There is probably about a week of work here at least for the API + extra for the installer/VSIX.

**Comment by Jax89** [comment]
I also will miss this plug-in a lot. Especially when working with multiple languages including R using VS is much more convenient than having to use RStudio as IDE only for R. While RStudio is a great IDE it still feels like it is more tailored to R data scientist than actual software developers which use R as part of their codebase.

**Comment by MikhailArkhipov** [comment]
Try https://github.com/microsoft/RTVS/tree/2019/vsix. This is totally unofficial port by me. RTVS is large and although I may tweak it occasionally, I have daytime job and other commitments :-)

**Comment by MNRK01** [comment]
Wow, thanks!!! One issue that I noticed is that starting the Variable Explorer window generates an exception "Exception has been thrown by the target of an invocation".

But, generally a huge thanks for giving the R community a pathway to using VS 2019!

**Comment by MikhailArkhipov** [comment]
@MNRK01 - which VS version is it in Help |  About? Mine is 16.0.2. Preview

**Comment by MNRK01** [comment]
Hi,

I'm at 16.1.3. Also reconfirming that the exception is still occurring after rebooting (just to be certain).

Full info is:

```
Microsoft Visual Studio Community 2019
Version 16.1.3
VisualStudio.16.Release/16.1.3+29009.5
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C++ 2019   00435-60000-00000-AA111
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.1.429.50124
ASP.NET and Web Tools 2019

C# Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Cookiecutter   16.1.19129.1
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Intel® Parallel Studio XE 2019 Update 4 Composer Edition for Fortran Windows*   Package ID: w_comp_lib_2019.4.228
Intel® Parallel Studio XE 2019 Update 4 Composer Edition for Fortran Windows* Integration for Microsoft Visual Studio* 2019, Version 19.0.0052.16, Copyright © 2002-2019 Intel Corporation. All rights reserved.
* Other names and brands may be claimed as the property of others.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Python   16.1.19129.1
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Python - IronPython support   16.1.19129.1
Provides templates and integration for IronPython-based projects.

Python - Profiling support   16.1.19129.1
Profiling support for Python projects.

R Tools for Visual Studio   1.5.50609.2148
Provides project system, R Interactive window, plotting, and more for the R programming language.

TermWindow Extension   1.0
TermWindow Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.10506.2004
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.1.1-beta4-19281-06+58a4b1e79aea28115e66b06f850c83a3f1fcb6d3
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake
```

**Comment by MikhailArkhipov** [comment]
Fixed. Please uninstall from Tools | Extensions and re-download new vsix.

**Comment by MNRK01** [comment]
Downloaded and installed the new VSIX. I can confirm that the Variable Explorer works well!

Thanks!!!

**Comment by MikhailArkhipov** [comment]
OK, closing this issue. I will publish to official store soon.

**Comment by MikhailArkhipov** [comment]
https://marketplace.visualstudio.com/items?itemName=MikhailArkhipov007.RTVS2019

**Comment by mkoohafkan** [comment]
@MikhailArkhipov I have been unable to get this working in VS 2019. I have tried a fresh install of VS 2019 but still get the ambiguous "One or more errors occurred" message when trying to create a new R project. Can you provide guidance on if there are any specific extensions or workloads that need to be installed in order for RTVS 2019 to work?

**Comment by MikhailArkhipov** [comment]
There are usually logs in C:\Users\USER_NAME\AppData\Roaming\Microsoft\VisualStudio\16.0*, such as ActivityLog and generally *.log. Check if any were create and attach them here.

**Comment by mkoohafkan** [comment]
Unfortunately there are no .log files that I can find in either of the two locations `16.0`, `16.0_4f391d83` in my `AppData\Roaming\Microsoft\VisualStudio` folder.

The closest relevant thing I found was in `ActivityLog.Setup.xml` 
```xml
  <entry>
    <record>2350</record>
    <time>2019/08/12 19:49:42.113</time>
    <type>Warning</type>
    <source>Project Template Metadata</source>
    <description>No template metadata found for ID: Microsoft.RTools.Project.Empty</description>
  </entry>
```

**Comment by MikhailArkhipov** [comment]
Try event viewer ->application and see if there are any recent error events with `devenv.exe`

**Comment by mkoohafkan** [comment]
Nothing from `devenv.exe`---but trying to create a new R project in VS2019 does produce errors for `Perflib`

```
The Open Procedure for service "Lsa" in DLL "C:\Windows\System32\Secur32.dll" failed. Performance data for this service will not be available. The first four bytes (DWORD) of the Data section contains the error code.
The Open Procedure for service "MSDTC" in DLL "C:\WINDOWS\system32\msdtcuiu.DLL" failed. Performance data for this service will not be available. The first four bytes (DWORD) of the Data section contains the error code.
The Open Procedure for service "WmiApRpl" in DLL "C:\WINDOWS\system32\wbem\wmiaprpl.dll" failed. Performance data for this service will not be available. The first four bytes (DWORD) of the Data section contains the error code.
```
and `PerfNet`
```
Unable to open the Server service performance object. The first four bytes (DWORD) of the Data section contains the status code.
```

**Comment by mkoohafkan** [comment]
Tried again with a fresh windows install and fresh VS2019 install---I still get the same failure, but now there is an [Activity Monitor Log](https://github.com/microsoft/RTVS/files/3561448/Activity.Monitor.Log.pdf):

```xml
<?xml version="1.0" encoding="utf-16"?>
<?xml-stylesheet type="text/xsl" href="ActivityLog.xsl"?>
<activity>
  <entry>
    <record>1</record>
    <time>2019/08/30 20:24:40.640</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Microsoft Visual Studio 2019 version: 16.0.29213.200</description>
  </entry>
  <entry>
    <record>2</record>
    <time>2019/08/30 20:24:40.640</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Log ID</description>
    <guid>{0D68DB35-6338-4858-902A-0D16CD1DFFAE}</guid>
  </entry>
  <entry>
    <record>3</record>
    <time>2019/08/30 20:24:40.642</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Running in isolation mode.</description>
  </entry>
  <entry>
    <record>4</record>
    <time>2019/08/30 20:24:40.671</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Looking for master PkgDef file</description>
    <path>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\master.pkgdef</path>
  </entry>
  <entry>
    <record>5</record>
    <time>2019/08/30 20:24:40.675</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Creating PkgDefCacheNonVolatile</description>
  </entry>
  <entry>
    <record>6</record>
    <time>2019/08/30 20:24:40.675</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>PkgDefCache flags</description>
    <hr>00013801</hr>
  </entry>
  <entry>
    <record>7</record>
    <time>2019/08/30 20:24:40.677</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Double-checking master pkgdef file</description>
  </entry>
  <entry>
    <record>8</record>
    <time>2019/08/30 20:24:40.678</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>PkgDefManagement initialized</description>
  </entry>
  <entry>
    <record>9</record>
    <time>2019/08/30 20:24:40.678</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>RootFolder</description>
    <path>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\</path>
  </entry>
  <entry>
    <record>10</record>
    <time>2019/08/30 20:24:40.678</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>ShellFolder</description>
    <path>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\</path>
  </entry>
  <entry>
    <record>53</record>
    <time>2019/08/30 20:24:43.370</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Loading UI library</description>
    <guid>{2FFE45C4-5C73-493C-B187-F2E955FF875E}</guid>
    <hr>800a006f</hr>
    <errorinfo>Cannot find the requested resource: 'Menus.ctmenu'.</errorinfo>
  </entry>
  <entry>
    <record>54</record>
    <time>2019/08/30 20:24:43.370</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Error loading UI library for package Microsoft.VisualStudio.LanguageServices.TypeScript.TypeScriptPackage, Microsoft.VisualStudio.LanguageServices.TypeScript, Version=16.0.0.0, Culture=neutral. HrLoadNativeUILibrary failed with 0x800a006f.</description>
  </entry>
  <entry>
    <record>56</record>
    <time>2019/08/30 20:24:43.382</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Failed to find CTMENU resource &apos;#1000&apos; in loaded UI library.</description>
  </entry>
  <entry>
    <record>57</record>
    <time>2019/08/30 20:24:43.457</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Loading UI library</description>
    <guid>{2EF1EC52-C8BF-4FE0-8ECE-BA9C0D5D1603}</guid>
    <hr>800a006f</hr>
    <errorinfo>Cannot find the requested resource: 'VSMenus.ctmenu'.</errorinfo>
  </entry>
  <entry>
    <record>58</record>
    <time>2019/08/30 20:24:43.457</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Error loading UI library for package XamlLanguagePackage. HrLoadNativeUILibrary failed with 0x800a006f.</description>
  </entry>
  <entry>
    <record>59</record>
    <time>2019/08/30 20:24:43.571</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Loading UI library</description>
    <guid>{71054795-27FD-4816-9AEA-667FE14EDD2A}</guid>
    <hr>800a006f</hr>
    <errorinfo>Cannot find the requested resource: 'DialogCommandPackage.ctmenu'.</errorinfo>
  </entry>
  <entry>
    <record>60</record>
    <time>2019/08/30 20:24:43.571</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>Error loading UI library for package New Project Dialog. HrLoadNativeUILibrary failed with 0x800a006f.</description>
  </entry>
  <entry>
    <record>383</record>
    <time>2019/08/30 20:24:46.408</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WORKFLOWDESIGNER\</path>
  </entry>
  <entry>
    <record>384</record>
    <time>2019/08/30 20:24:46.408</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WORKFLOWDESIGNER\</path>
  </entry>
  <entry>
    <record>385</record>
    <time>2019/08/30 20:24:46.410</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WORKFLOWDESIGNERCOLORS\</path>
  </entry>
  <entry>
    <record>386</record>
    <time>2019/08/30 20:24:46.410</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WORKFLOWDESIGNERCOLORS\</path>
  </entry>
  <entry>
    <record>387</record>
    <time>2019/08/30 20:24:46.412</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\XAMLDIAGNOSTICS\</path>
  </entry>
  <entry>
    <record>388</record>
    <time>2019/08/30 20:24:46.412</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\XAMLDIAGNOSTICS\</path>
  </entry>
  <entry>
    <record>389</record>
    <time>2019/08/30 20:24:46.413</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\XAMLLANGUAGESERVICE\</path>
  </entry>
  <entry>
    <record>390</record>
    <time>2019/08/30 20:24:46.413</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\XAMLLANGUAGESERVICE\</path>
  </entry>
  <entry>
    <record>391</record>
    <time>2019/08/30 20:24:46.415</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\CPUSAMPLING\</path>
  </entry>
  <entry>
    <record>392</record>
    <time>2019/08/30 20:24:46.415</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\CPUSAMPLING\</path>
  </entry>
  <entry>
    <record>393</record>
    <time>2019/08/30 20:24:46.416</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\DEBUGGER\</path>
  </entry>
  <entry>
    <record>394</record>
    <time>2019/08/30 20:24:46.416</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\DEBUGGER\</path>
  </entry>
  <entry>
    <record>395</record>
    <time>2019/08/30 20:24:46.418</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\DIAGNOSTICSHUB\</path>
  </entry>
  <entry>
    <record>396</record>
    <time>2019/08/30 20:24:46.418</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\DIAGNOSTICSHUB\</path>
  </entry>
  <entry>
    <record>397</record>
    <time>2019/08/30 20:24:46.419</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\DOTNETOBJECTALLOC\</path>
  </entry>
  <entry>
    <record>398</record>
    <time>2019/08/30 20:24:46.419</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\DOTNETOBJECTALLOC\</path>
  </entry>
  <entry>
    <record>399</record>
    <time>2019/08/30 20:24:46.420</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\INSTRUMENTATION\</path>
  </entry>
  <entry>
    <record>400</record>
    <time>2019/08/30 20:24:46.420</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\INSTRUMENTATION\</path>
  </entry>
  <entry>
    <record>401</record>
    <time>2019/08/30 20:24:46.421</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\PARALLELDEBUGGER\</path>
  </entry>
  <entry>
    <record>402</record>
    <time>2019/08/30 20:24:46.422</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\PARALLELDEBUGGER\</path>
  </entry>
  <entry>
    <record>403</record>
    <time>2019/08/30 20:24:46.423</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\PERFMARKERS\</path>
  </entry>
  <entry>
    <record>404</record>
    <time>2019/08/30 20:24:46.423</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\PERFMARKERS\</path>
  </entry>
  <entry>
    <record>405</record>
    <time>2019/08/30 20:24:46.425</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\SHELL\</path>
  </entry>
  <entry>
    <record>406</record>
    <time>2019/08/30 20:24:46.425</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\SHELL\</path>
  </entry>
  <entry>
    <record>407</record>
    <time>2019/08/30 20:24:46.428</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\TREENAVIGATION\</path>
  </entry>
  <entry>
    <record>408</record>
    <time>2019/08/30 20:24:46.428</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\TREENAVIGATION\</path>
  </entry>
  <entry>
    <record>409</record>
    <time>2019/08/30 20:24:46.432</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\ARCHITECTURE TOOLS\GRAPHPROVIDERPACKAGE\</path>
  </entry>
  <entry>
    <record>410</record>
    <time>2019/08/30 20:24:46.432</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\ARCHITECTURE TOOLS\GRAPHPROVIDERPACKAGE\</path>
  </entry>
  <entry>
    <record>411</record>
    <time>2019/08/30 20:24:46.434</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\ASREXTENSIONS\SHAREPOINT\</path>
  </entry>
  <entry>
    <record>412</record>
    <time>2019/08/30 20:24:46.434</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\ASREXTENSIONS\SHAREPOINT\</path>
  </entry>
  <entry>
    <record>413</record>
    <time>2019/08/30 20:24:46.436</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CLIENTDIAGNOSTICS\APPRESPONSIVENESS\</path>
  </entry>
  <entry>
    <record>414</record>
    <time>2019/08/30 20:24:46.436</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CLIENTDIAGNOSTICS\APPRESPONSIVENESS\</path>
  </entry>
  <entry>
    <record>415</record>
    <time>2019/08/30 20:24:46.438</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\EDITORCONFIG\WIZARD\</path>
  </entry>
  <entry>
    <record>416</record>
    <time>2019/08/30 20:24:46.438</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\EDITORCONFIG\WIZARD\</path>
  </entry>
  <entry>
    <record>417</record>
    <time>2019/08/30 20:24:46.439</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\EXTENSIONMANAGER\SERVICEMODULE\</path>
  </entry>
  <entry>
    <record>418</record>
    <time>2019/08/30 20:24:46.439</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\EXTENSIONMANAGER\SERVICEMODULE\</path>
  </entry>
  <entry>
    <record>419</record>
    <time>2019/08/30 20:24:46.440</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\GETTINGSTARTEDTEMPLATES\RESOURCES\</path>
  </entry>
  <entry>
    <record>420</record>
    <time>2019/08/30 20:24:46.440</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\GETTINGSTARTEDTEMPLATES\RESOURCES\</path>
  </entry>
  <entry>
    <record>421</record>
    <time>2019/08/30 20:24:46.442</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\LANGUAGE\GENERATETYPE\</path>
  </entry>
  <entry>
    <record>422</record>
    <time>2019/08/30 20:24:46.442</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\LANGUAGE\GENERATETYPE\</path>
  </entry>
  <entry>
    <record>423</record>
    <time>2019/08/30 20:24:46.443</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TEAMFOUNDATION\TEAM EXPLORER\</path>
  </entry>
  <entry>
    <record>424</record>
    <time>2019/08/30 20:24:46.443</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\TEAMFOUNDATION\TEAM EXPLORER\</path>
  </entry>
  <entry>
    <record>425</record>
    <time>2019/08/30 20:24:46.445</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\VC\DEBUGGER\</path>
  </entry>
  <entry>
    <record>426</record>
    <time>2019/08/30 20:24:46.445</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\VC\DEBUGGER\</path>
  </entry>
  <entry>
    <record>427</record>
    <time>2019/08/30 20:24:46.446</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\VISUALSTUDIO\EDITORS\</path>
  </entry>
  <entry>
    <record>428</record>
    <time>2019/08/30 20:24:46.446</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\VISUALSTUDIO\EDITORS\</path>
  </entry>
  <entry>
    <record>429</record>
    <time>2019/08/30 20:24:46.448</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEB\ASPX\</path>
  </entry>
  <entry>
    <record>430</record>
    <time>2019/08/30 20:24:46.448</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEB\ASPX\</path>
  </entry>
  <entry>
    <record>431</record>
    <time>2019/08/30 20:24:46.451</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEB\EXPORTS\</path>
  </entry>
  <entry>
    <record>432</record>
    <time>2019/08/30 20:24:46.451</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEB\EXPORTS\</path>
  </entry>
  <entry>
    <record>433</record>
    <time>2019/08/30 20:24:46.454</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\NAVIGATETO\FILEPROVIDER\</path>
  </entry>
  <entry>
    <record>434</record>
    <time>2019/08/30 20:24:46.454</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\NAVIGATETO\FILEPROVIDER\</path>
  </entry>
  <entry>
    <record>435</record>
    <time>2019/08/30 20:24:46.456</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\TREENAVIGATION\GRAPHPROVIDER\</path>
  </entry>
  <entry>
    <record>436</record>
    <time>2019/08/30 20:24:46.456</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\TREENAVIGATION\GRAPHPROVIDER\</path>
  </entry>
  <entry>
    <record>437</record>
    <time>2019/08/30 20:24:46.458</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\VISUAL STUDIO MPF\16.0\</path>
  </entry>
  <entry>
    <record>438</record>
    <time>2019/08/30 20:24:46.458</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\PLATFORM\VISUAL STUDIO MPF\16.0\</path>
  </entry>
  <entry>
    <record>439</record>
    <time>2019/08/30 20:24:46.460</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\ARCHITECTURE TOOLS\PROVIDERS\MANAGEDPROVIDER\</path>
  </entry>
  <entry>
    <record>440</record>
    <time>2019/08/30 20:24:46.460</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\ARCHITECTURE TOOLS\PROVIDERS\MANAGEDPROVIDER\</path>
  </entry>
  <entry>
    <record>441</record>
    <time>2019/08/30 20:24:46.462</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\ARCHITECTURE TOOLS\PROVIDERS\SOLUTION\</path>
  </entry>
  <entry>
    <record>442</record>
    <time>2019/08/30 20:24:46.462</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\ARCHITECTURE TOOLS\PROVIDERS\SOLUTION\</path>
  </entry>
  <entry>
    <record>443</record>
    <time>2019/08/30 20:24:46.463</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\EXPRESSIONEVALUATORS\</path>
  </entry>
  <entry>
    <record>444</record>
    <time>2019/08/30 20:24:46.463</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\EXPRESSIONEVALUATORS\</path>
  </entry>
  <entry>
    <record>445</record>
    <time>2019/08/30 20:24:46.465</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\INTERACTIVECOMPONENTS\</path>
  </entry>
  <entry>
    <record>446</record>
    <time>2019/08/30 20:24:46.465</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\INTERACTIVECOMPONENTS\</path>
  </entry>
  <entry>
    <record>447</record>
    <time>2019/08/30 20:24:46.466</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\LANGUAGESERVICES\</path>
  </entry>
  <entry>
    <record>448</record>
    <time>2019/08/30 20:24:46.466</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\LANGUAGESERVICES\</path>
  </entry>
  <entry>
    <record>449</record>
    <time>2019/08/30 20:24:46.467</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\SOURCEBASEDTESTDISCOVERY\</path>
  </entry>
  <entry>
    <record>450</record>
    <time>2019/08/30 20:24:46.467</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\MANAGEDLANGUAGES\VBCSHARP\SOURCEBASEDTESTDISCOVERY\</path>
  </entry>
  <entry>
    <record>451</record>
    <time>2019/08/30 20:24:46.469</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEB\RAZOR\V3.0\</path>
  </entry>
  <entry>
    <record>452</record>
    <time>2019/08/30 20:24:46.469</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEB\RAZOR\V3.0\</path>
  </entry>
  <entry>
    <record>453</record>
    <time>2019/08/30 20:24:46.471</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEBCLIENT\DIAGNOSTICS\TOOLWINDOWS\</path>
  </entry>
  <entry>
    <record>454</record>
    <time>2019/08/30 20:24:46.471</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEBCLIENT\DIAGNOSTICS\TOOLWINDOWS\</path>
  </entry>
  <entry>
    <record>455</record>
    <time>2019/08/30 20:24:46.475</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEBCLIENT\DIAGNOSTICS\WEBDIAGNOSTICSATTACH\</path>
  </entry>
  <entry>
    <record>456</record>
    <time>2019/08/30 20:24:46.475</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\WEBCLIENT\DIAGNOSTICS\WEBDIAGNOSTICSATTACH\</path>
  </entry>
  <entry>
    <record>457</record>
    <time>2019/08/30 20:24:46.476</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Successfully loaded extension...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\EXTENSIONS\2NPDPF5S.NHQ\</path>
  </entry>
  <entry>
    <record>458</record>
    <time>2019/08/30 20:24:46.476</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Extension is enabled...</description>
    <path>C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\EXTENSIONS\2NPDPF5S.NHQ\</path>
  </entry>
  <entry>
    <record>459</record>
    <time>2019/08/30 20:24:46.554</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Visual Studio CRC package]</description>
    <guid>{6B238C39-B163-467E-83DB-A2DEC10459ED}</guid>
  </entry>
  <entry>
    <record>460</record>
    <time>2019/08/30 20:24:46.600</time>
    <type>Warning</type>
    <source>CommonIDEPackage</source>
    <description>About to block on async service creation because the service was requested via GetService. This has the potential to deadlock. Async initializing services should be retrieved via GetServiceAsync.</description>
  </entry>
  <entry>
    <record>461</record>
    <time>2019/08/30 20:24:46.601</time>
    <type>Warning</type>
    <source>CommonIDEPackage</source>
    <description>About to block on async service creation because the service was requested via GetService. This has the potential to deadlock. Async initializing services should be retrieved via GetServiceAsync.</description>
  </entry>
  <entry>
    <record>462</record>
    <time>2019/08/30 20:24:46.602</time>
    <type>Warning</type>
    <source>CommonIDEPackage</source>
    <description>About to block on async service creation because the service was requested via GetService. This has the potential to deadlock. Async initializing services should be retrieved via GetServiceAsync.</description>
  </entry>
  <entry>
    <record>463</record>
    <time>2019/08/30 20:24:46.602</time>
    <type>Warning</type>
    <source>CommonIDEPackage</source>
    <description>About to block on async service creation because the service was requested via GetService. This has the potential to deadlock. Async initializing services should be retrieved via GetServiceAsync.</description>
  </entry>
  <entry>
    <record>464</record>
    <time>2019/08/30 20:24:47.853</time>
    <type>Information</type>
    <source>UIDelayNotifications</source>
    <description>UI-delay processor started successfully.</description>
  </entry>
  <entry>
    <record>465</record>
    <time>2019/08/30 20:24:47.853</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Visual Studio CRC package]</description>
    <guid>{6B238C39-B163-467E-83DB-A2DEC10459ED}</guid>
  </entry>
  <entry>
    <record>466</record>
    <time>2019/08/30 20:24:47.854</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Skipping &apos;C:\Program Files (x86)\Common Files\Microsoft\ExtensionManager\Extensions&apos; as it doesn&apos;t exist</description>
  </entry>
  <entry>
    <record>467</record>
    <time>2019/08/30 20:24:47.854</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Searching folder for extension.vsixmanifest files...</description>
    <path>C:\Program Files (x86)\Microsoft SDKs</path>
  </entry>
  <entry>
    <record>468</record>
    <time>2019/08/30 20:24:47.895</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Microsoft.VisualStudio.Shell.Connected.Packages.OnlineLicensing.OnlineLicensingManagerPackage]</description>
    <guid>{A5C25D8F-4D74-4924-BD8C-F3C2B860F4EC}</guid>
  </entry>
  <entry>
    <record>469</record>
    <time>2019/08/30 20:24:47.898</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Microsoft.VisualStudio.Shell.Connected.Packages.OnlineLicensing.OnlineLicensingManagerPackage]</description>
    <guid>{A5C25D8F-4D74-4924-BD8C-F3C2B860F4EC}</guid>
  </entry>
  <entry>
    <record>470</record>
    <time>2019/08/30 20:24:47.965</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Microsoft.VisualStudio.Shell.Connected.ConnectedUser.ConnectedUserPackage]</description>
    <guid>{7F679D93-2EB6-47C9-85EB-F6AD16902662}</guid>
  </entry>
  <entry>
    <record>471</record>
    <time>2019/08/30 20:24:47.981</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Microsoft.VisualStudio.Shell.Connected.ConnectedUser.ConnectedUserPackage]</description>
    <guid>{7F679D93-2EB6-47C9-85EB-F6AD16902662}</guid>
  </entry>
  <entry>
    <record>472</record>
    <time>2019/08/30 20:24:48.008</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [Microsoft.VisualStudio.Services.ToastNotifications.ToastNotificationsPackage]</description>
    <guid>{C931D979-CA1A-41E8-8A23-E86B85E3141B}</guid>
  </entry>
  <entry>
    <record>473</record>
    <time>2019/08/30 20:24:48.016</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [Microsoft.VisualStudio.Services.ToastNotifications.ToastNotificationsPackage]</description>
    <guid>{C931D979-CA1A-41E8-8A23-E86B85E3141B}</guid>
  </entry>
  <entry>
    <record>474</record>
    <time>2019/08/30 20:24:48.086</time>
    <type>Information</type>
    <source>UserConnection</source>
    <description>Manager ServerUri &apos;https://go.microsoft.com/fwlink/?LinkID=660932&apos;</description>
  </entry>
  <entry>
    <record>475</record>
    <time>2019/08/30 20:24:48.196</time>
    <type>Information</type>
    <source>Extension Manager</source>
    <description>Skipping &apos;C:\Users\mkoohafk\AppData\Local\Microsoft SDKs&apos; as it doesn&apos;t exist</description>
  </entry>
  <entry>
    <record>476</record>
    <time>2019/08/30 20:24:48.276</time>
    <type>Information</type>
    <source>UserConnection</source>
    <description>Unresolved FW Link &apos;https://go.microsoft.com/fwlink/?LinkID=660932&apos; was resolved to &apos;https://app.vssps.visualstudio.com/&apos;</description>
  </entry>
  <entry>
    <record>477</record>
    <time>2019/08/30 20:24:48.444</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [IntelliCodePackage]</description>
    <guid>{237BDE42-2754-4B15-ADBD-0B6CECE84300}</guid>
  </entry>
  <entry>
    <record>478</record>
    <time>2019/08/30 20:24:48.484</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [HostPackage]</description>
    <guid>{49D12072-378B-4FFA-A09E-40E0B5D097CC}</guid>
  </entry>
  <entry>
    <record>479</record>
    <time>2019/08/30 20:24:48.494</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>End package load [HostPackage]</description>
    <guid>{49D12072-378B-4FFA-A09E-40E0B5D097CC}</guid>
  </entry>
  <entry>
    <record>480</record>
    <time>2019/08/30 20:24:49.666</time>
    <type>Information</type>
    <source>ClientRights</source>
    <description>The clients rights token could not be found</description>
  </entry>
  <entry>
    <record>481</record>
    <time>2019/08/30 20:24:50.076</time>
    <type>Information</type>
    <source>ClientRights</source>
    <description>Client rights determined: {&quot;CurrentClientRights&quot;:{&quot;LicenseSource&quot;:0,&quot;LicenseSource2&quot;:0,&quot;IsSubscriptionBased&quot;:false,&quot;DaysSinceCreation&quot;:-1,&quot;LicenseType&quot;:2,&quot;AuthorizedVsEdition&quot;:0,&quot;AuthorizedVsEdition2&quot;:200,&quot;DaysToExpire&quot;:30,&quot;IsLicenseGood&quot;:true,&quot;LicenseDescription&quot;:&quot;30 day trial (for evaluation purposes only)&quot;,&quot;LicenseStatus&quot;:2,&quot;LicenseUrl&quot;:&quot;&quot;,&quot;MayUplevel&quot;:false,&quot;LicensedUserId&quot;:&quot;00000000-0000-0000-0000-000000000000&quot;,&quot;LicensedUserName&quot;:&quot;&quot;,&quot;LicensingAccount&quot;:&quot;&quot;,&quot;ReleaseType&quot;:1},&quot;CurrentLicenseSource&quot;:0,&quot;CurrentLicenseSource2&quot;:0,&quot;IDEUserClientRights&quot;:null,&quot;PIDClientRights&quot;:{&quot;LicenseSource&quot;:0,&quot;LicenseSource2&quot;:0,&quot;IsSubscriptionBased&quot;:false,&quot;DaysSinceCreation&quot;:-1,&quot;LicenseType&quot;:2,&quot;AuthorizedVsEdition&quot;:0,&quot;AuthorizedVsEdition2&quot;:200,&quot;DaysToExpire&quot;:30,&quot;IsLicenseGood&quot;:true,&quot;LicenseDescription&quot;:&quot;30 day trial (for evaluation purposes only)&quot;,&quot;LicenseStatus&quot;:2,&quot;LicenseUrl&quot;:&quot;&quot;,&quot;MayUplevel&quot;:false,&quot;LicensedUserId&quot;:&quot;00000000-0000-0000-0000-000000000000&quot;,&quot;LicensedUserName&quot;:&quot;&quot;,&quot;LicensingAccount&quot;:&quot;&quot;,&quot;ReleaseType&quot;:1}}; Account identity provider: </description>
  </entry>
  <entry>
    <record>482</record>
    <time>2019/08/30 20:24:50.968</time>
    <type></type>
    <source>VisualStudio</source>
    <description>Destroying Main Window</description>
  </entry>
</activity>
```
